version: "3"
services:
  adminer:
    image: adminer
    ports:
      - 8081:8080

  angular:
    image: trion/ng-cli:latest
    volumes:
      - ./frontend:/app
    ports:
      - 4200:4200
    command: "npm start"
